# Generated by Django 3.2.25 on 2024-11-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('teacher', '教师'), ('student', '学生'), ('parent', '家长')], default='student', max_length=20),
        ),
    ]
