# Generated by Django 3.2.25 on 2024-11-18 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_alter_profile_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectStudentTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='学生姓名')),
                ('student_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='学生手机号')),
                ('student_sex', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=20, verbose_name='学生性别')),
                ('relationship', models.CharField(choices=[('老师', '老师'), ('父亲', '父亲'), ('母亲', '母亲')], default='老师', max_length=20, verbose_name='与学生的关系')),
                ('teacher_or_parent_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='老师/家长姓名')),
                ('teacher_or_parent_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='老师/家长手机号')),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='student_image', verbose_name='学生照片')),
                ('connect_time', models.DateTimeField(auto_now_add=True, verbose_name='关联时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_connections', to='login.profile', verbose_name='学生账号')),
                ('teacher_or_parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_or_parent_connection', to='login.profile', verbose_name='老师/家长账号')),
            ],
            options={
                'verbose_name': '学生与教师/家长关联',
                'verbose_name_plural': '学生与教师/家长关联',
            },
        ),
    ]
