# Generated by Django 4.2.16 on 2024-11-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AI_analyse", "0002_connectstudentteacher_student_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectstudentteacher",
            name="student_code",
            field=models.CharField(max_length=100, verbose_name="学生密码"),
        ),
    ]
