# Generated by Django 4.2.16 on 2024-11-20 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0002_alter_profile_user_type"),
        ("AI_analyse", "0003_alter_connectstudentteacher_student_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectstudentteacher",
            name="teacher_or_parent",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_or_parent_connection",
                to="login.profile",
                verbose_name="老师/家长账号",
            ),
        ),
    ]
