# Generated by Django 4.2.16 on 2024-11-20 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0002_alter_profile_user_type"),
        ("AI_analyse", "0004_alter_connectstudentteacher_teacher_or_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectstudentteacher",
            name="teacher_or_parent",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_or_parent_connection",
                to="login.profile",
                verbose_name="老师/家长账号",
            ),
            preserve_default=False,
        ),
    ]
