# Generated by Django 3.2.25 on 2024-11-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='img_draw')),
                ('category', models.CharField(choices=[('original', '原创'), ('inspiration', '灵感'), ('copy', '临摹')], max_length=20)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
