# Generated by Django 3.2.25 on 2024-11-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw_banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(upload_to='F:\\ai_draw\\draw_banner\\static\\image_draw'),
        ),
    ]
