# Generated by Django 3.2.25 on 2024-11-08 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('draw_banner', '0003_alter_artwork_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='作品名称')),
                ('image', models.ImageField(upload_to='drawings/', verbose_name='绘画作品文件')),
                ('ai_analysis', models.TextField(blank=True, null=True, verbose_name='AI分析结果')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='留言')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '绘画作品',
                'verbose_name_plural': '绘画作品集',
            },
        ),
    ]
