# Generated by Django 4.2.16 on 2024-11-30 07:41

import AppreciationOfDrawing.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DrawingWarehouse",
            fields=[
                ("DrawingID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "DrawingName",
                    models.CharField(max_length=100, null=True, verbose_name="画作名字"),
                ),
                (
                    "DrawingSize",
                    models.CharField(max_length=30, null=True, verbose_name="画作大小"),
                ),
                (
                    "DrawingYear",
                    models.CharField(max_length=20, null=True, verbose_name="画作年份"),
                ),
                (
                    "DrawingPicture",
                    models.ImageField(
                        upload_to=AppreciationOfDrawing.models.drawing_image_path,
                        verbose_name="画作图片",
                    ),
                ),
                (
                    "DrawingTag",
                    models.CharField(
                        choices=[
                            ("中国画", "中国画"),
                            ("油画", "油画"),
                            ("版画", "版画"),
                            ("雕塑", "雕塑"),
                            ("素描 速写", "素描 速写"),
                            ("摄影", "摄影"),
                            ("水彩 水粉 色粉", "水彩 水粉 色粉"),
                            ("漫画", "漫画"),
                            ("连环画", "连环画"),
                            ("漆画", "漆画"),
                            ("书法 篆刻", "书法 篆刻"),
                            ("新年画", "新年画"),
                            ("插图", "插图"),
                            ("现代装置", "现代装置"),
                            ("综合艺术", "综合艺术"),
                        ],
                        max_length=20,
                        verbose_name="画作标签",
                    ),
                ),
                (
                    "feekback",
                    models.CharField(max_length=100, null=True, verbose_name="画作评价"),
                ),
                ("likes", models.PositiveIntegerField(default=0, verbose_name="点赞数")),
                ("views", models.PositiveIntegerField(default=0, verbose_name="浏览量")),
                ("clicks", models.PositiveIntegerField(default=0, verbose_name="点击数")),
                (
                    "favorites",
                    models.PositiveIntegerField(default=0, verbose_name="收藏数"),
                ),
            ],
            options={
                "verbose_name": "画作信息",
                "verbose_name_plural": "画作信息",
            },
        ),
        migrations.CreateModel(
            name="MyLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("liked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "drawing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liked_by",
                        to="AppreciationOfDrawing.drawingwarehouse",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "drawing")},
            },
        ),
    ]
